CREATE TABLE agreement (id BIGINT PRIMARY KEY, tenant_id BIGINT NOT NULL, agreement_no VARCHAR(64) NOT NULL, agreement_type VARCHAR(32) NOT NULL, customer_id BIGINT NOT NULL, source_opportunity_id BIGINT NULL, source_quotation_version_id BIGINT NOT NULL, source_reservation_id BIGINT NOT NULL, previous_agreement_id BIGINT NULL, sign_time DATETIME(3) NULL, start_time DATETIME(3) NOT NULL, end_time DATETIME(3) NOT NULL, currency CHAR(3) NOT NULL, total_amount DECIMAL(18,2) NOT NULL, deposit_amount DECIMAL(18,2) NOT NULL DEFAULT 0, status VARCHAR(32) NOT NULL, expiry_stage VARCHAR(16) NOT NULL DEFAULT 'NONE', workflow_instance_id VARCHAR(128) NULL, version INT NOT NULL DEFAULT 0, created_at DATETIME(3) NOT NULL, updated_at DATETIME(3) NOT NULL, UNIQUE KEY uk_agreement(tenant_id,agreement_no), KEY idx_ag_customer(tenant_id,customer_id,status), KEY idx_ag_expiry(tenant_id,status,end_time,id));
CREATE TABLE agreement_item (id BIGINT PRIMARY KEY, tenant_id BIGINT NOT NULL, agreement_id BIGINT NOT NULL, resource_unit_id BIGINT NOT NULL, offering_id BIGINT NOT NULL, start_time DATETIME(3) NOT NULL, end_time DATETIME(3) NOT NULL, unit_price DECIMAL(20,8) NOT NULL, quantity DECIMAL(20,6) NOT NULL DEFAULT 1, discount_amount DECIMAL(18,2) NOT NULL DEFAULT 0, amount DECIMAL(18,2) NOT NULL, effective_from DATETIME(3) NOT NULL, effective_to DATETIME(3) NULL, status VARCHAR(32) NOT NULL, KEY idx_ag_item_res(tenant_id,resource_unit_id,start_time,end_time));
CREATE TABLE agreement_snapshot (id BIGINT PRIMARY KEY, tenant_id BIGINT NOT NULL, agreement_id BIGINT NOT NULL, snapshot_version INT NOT NULL, snapshot_type VARCHAR(32) NOT NULL, payload JSON NOT NULL, created_at DATETIME(3) NOT NULL, UNIQUE KEY uk_ag_snapshot(tenant_id,agreement_id,snapshot_version,snapshot_type));
CREATE TABLE agreement_change (id BIGINT PRIMARY KEY, tenant_id BIGINT NOT NULL, agreement_id BIGINT NOT NULL, change_no VARCHAR(64) NOT NULL, change_type VARCHAR(32) NOT NULL, effective_date DATETIME(3) NOT NULL, reason VARCHAR(1024) NULL, before_snapshot JSON NOT NULL, after_snapshot JSON NOT NULL, workflow_instance_id VARCHAR(128) NULL, status VARCHAR(32) NOT NULL, created_at DATETIME(3) NOT NULL, UNIQUE KEY uk_ag_change(tenant_id,change_no), KEY idx_ag_change_ag(tenant_id,agreement_id,status));
CREATE TABLE agreement_sign_process (id BIGINT PRIMARY KEY, tenant_id BIGINT NOT NULL, agreement_id BIGINT NOT NULL, reservation_id BIGINT NOT NULL, process_status VARCHAR(32) NOT NULL, asset_commit_status VARCHAR(32) NOT NULL, agreement_commit_status VARCHAR(32) NOT NULL, retry_count INT NOT NULL DEFAULT 0, last_error TEXT NULL, request_id VARCHAR(128) NOT NULL, updated_at DATETIME(3) NOT NULL, UNIQUE KEY uk_sign_request(tenant_id,request_id), UNIQUE KEY uk_sign_agreement(tenant_id,agreement_id));
CREATE TABLE renewal_priority (id BIGINT PRIMARY KEY, tenant_id BIGINT NOT NULL, agreement_id BIGINT NOT NULL, customer_id BIGINT NOT NULL, resource_unit_id BIGINT NOT NULL, priority_start DATETIME(3) NOT NULL, priority_end DATETIME(3) NOT NULL, priority_mode VARCHAR(16) NOT NULL, status VARCHAR(32) NOT NULL, decision_at DATETIME(3) NULL, decision_by BIGINT NULL, decision_reason VARCHAR(512) NULL, KEY idx_renewal_res(tenant_id,resource_unit_id,status,priority_end));
CREATE TABLE handover_order (id BIGINT PRIMARY KEY, tenant_id BIGINT NOT NULL, handover_no VARCHAR(64) NOT NULL, agreement_id BIGINT NOT NULL, handover_type VARCHAR(16) NOT NULL, planned_at DATETIME(3) NULL, completed_at DATETIME(3) NULL, status VARCHAR(32) NOT NULL, signed_file_id BIGINT NULL, UNIQUE KEY uk_handover(tenant_id,handover_no), KEY idx_handover_ag(tenant_id,agreement_id,status));
CREATE TABLE handover_item (id BIGINT PRIMARY KEY, tenant_id BIGINT NOT NULL, handover_order_id BIGINT NOT NULL, item_type VARCHAR(32) NOT NULL, item_name VARCHAR(128) NOT NULL, before_value VARCHAR(512) NULL, after_value VARCHAR(512) NULL, amount DECIMAL(18,2) NULL, evidence_file_id BIGINT NULL);
CREATE TABLE signature_process (id BIGINT PRIMARY KEY, tenant_id BIGINT NOT NULL, agreement_id BIGINT NOT NULL, provider VARCHAR(32) NOT NULL, provider_process_no VARCHAR(128) NULL, status VARCHAR(32) NOT NULL, signed_file_id BIGINT NULL, file_sha256 VARCHAR(128) NULL, created_at DATETIME(3) NOT NULL, updated_at DATETIME(3) NOT NULL, UNIQUE KEY uk_sig_ag(tenant_id,agreement_id));
