CREATE TABLE agreement_party (
  id BIGINT NOT NULL,
  tenant_id BIGINT NOT NULL,
  agreement_id BIGINT NOT NULL,
  party_role VARCHAR(32) NOT NULL,
  party_type VARCHAR(32) NOT NULL,
  customer_id BIGINT NULL,
  organization_id BIGINT NULL,
  external_party_ref VARCHAR(128) NULL,
  legal_name_snapshot VARCHAR(256) NOT NULL,
  unified_credit_code_snapshot VARCHAR(64) NULL,
  id_number_masked_snapshot VARCHAR(128) NULL,
  contact_name_snapshot VARCHAR(128) NULL,
  phone_masked_snapshot VARCHAR(64) NULL,
  email_masked_snapshot VARCHAR(256) NULL,
  address_snapshot VARCHAR(512) NULL,
  bank_name_snapshot VARCHAR(256) NULL,
  bank_account_masked_snapshot VARCHAR(128) NULL,
  tax_no_snapshot VARCHAR(128) NULL,
  effective_from DATETIME(3) NOT NULL,
  effective_to DATETIME(3) NULL,
  status VARCHAR(32) NOT NULL,
  source_type VARCHAR(32) NOT NULL,
  source_id BIGINT NULL,
  version INT NOT NULL DEFAULT 0,
  created_by BIGINT NULL,
  created_at DATETIME(3) NOT NULL,
  updated_by BIGINT NULL,
  updated_at DATETIME(3) NOT NULL,
  PRIMARY KEY (id),
  KEY idx_agreement_party_active (tenant_id, agreement_id, party_role, status, effective_from)
);

CREATE TABLE resource_transfer (
  id BIGINT NOT NULL,
  tenant_id BIGINT NOT NULL,
  transfer_no VARCHAR(64) NOT NULL,
  agreement_id BIGINT NOT NULL,
  customer_id BIGINT NOT NULL,
  from_resource_unit_id BIGINT NOT NULL,
  to_resource_unit_id BIGINT NOT NULL,
  requested_effective_at DATETIME(3) NOT NULL,
  actual_effective_at DATETIME(3) NULL,
  reason_type VARCHAR(32) NOT NULL,
  reason VARCHAR(512) NULL,
  price_difference DECIMAL(18,2) NOT NULL DEFAULT 0,
  deposit_difference DECIMAL(18,2) NOT NULL DEFAULT 0,
  billing_impact_status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  status VARCHAR(32) NOT NULL,
  workflow_instance_id VARCHAR(128) NULL,
  version INT NOT NULL DEFAULT 0,
  created_by BIGINT NULL,
  created_at DATETIME(3) NOT NULL,
  updated_by BIGINT NULL,
  updated_at DATETIME(3) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_resource_transfer_no (tenant_id, transfer_no),
  KEY idx_resource_transfer_agreement (tenant_id, agreement_id, status),
  KEY idx_resource_transfer_target (tenant_id, to_resource_unit_id, requested_effective_at)
);
