package com.enterprise.iam.common.security.delegation;

public enum DelegationValidationFailure {
    MISSING_TOKEN,
    TOKEN_TOO_LARGE,
    MALFORMED_TOKEN,
    INVALID_SIGNATURE,
    ALGORITHM_NOT_ALLOWED,
    INVALID_TYPE,
    MISSING_KEY_ID,
    INVALID_KEY_ID,
    UNKNOWN_KEY_ID,
    KEY_RESOLUTION_UNAVAILABLE,
    INVALID_ISSUER,
    INVALID_AUDIENCE,
    INVALID_TIME_CLAIMS,
    TOKEN_NOT_YET_VALID,
    TOKEN_EXPIRED,
    TOKEN_TTL_EXCEEDED,
    MISSING_REQUIRED_CONTEXT
}
