<?xml version="1.0" encoding="UTF-8"?><project xmlns="http://maven.apache.org/POM/4.0.0"><modelVersion>4.0.0</modelVersion><parent><groupId>com.company.marketplace</groupId><artifactId>marketplace-business-framework</artifactId><version>${revision}</version><relativePath>../pom.xml</relativePath></parent><artifactId>marketplace-system</artifactId>
<dependencies><dependency><groupId>com.company.marketplace</groupId><artifactId>marketplace-common</artifactId><version>${revision}</version></dependency><dependency><groupId>com.company.marketplace</groupId><artifactId>marketplace-web</artifactId><version>${revision}</version></dependency><dependency><groupId>com.company.marketplace</groupId><artifactId>marketplace-security</artifactId><version>${revision}</version></dependency><dependency><groupId>com.company.marketplace</groupId><artifactId>marketplace-mybatis</artifactId><version>${revision}</version></dependency><dependency><groupId>com.alibaba.cloud</groupId><artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId></dependency></dependencies></project>
