CREATE TABLE trade (
 id BIGINT PRIMARY KEY,
 buyer_id BIGINT NOT NULL,
 trade_no VARCHAR(64) NOT NULL,
 currency CHAR(3) NOT NULL,
 goods_amount DECIMAL(18,2) NOT NULL,
 discount_amount DECIMAL(18,2) NOT NULL,
 shipping_amount DECIMAL(18,2) NOT NULL,
 tax_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
 payable_amount DECIMAL(18,2) NOT NULL,
 paid_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
 status VARCHAR(32) NOT NULL,
 expire_at DATETIME(3),
 version INT NOT NULL DEFAULT 0,
 created_at DATETIME(3) NOT NULL,
 updated_at DATETIME(3) NOT NULL,
 UNIQUE KEY uk_trade_no (trade_no),
 KEY idx_trade_buyer (buyer_id, created_at),
 KEY idx_trade_status_expire (status, expire_at)
);
CREATE TABLE merchant_order (
 id BIGINT PRIMARY KEY,
 trade_id BIGINT NOT NULL,
 buyer_id BIGINT NOT NULL,
 merchant_id BIGINT NOT NULL,
 shop_id BIGINT NOT NULL,
 order_no VARCHAR(64) NOT NULL,
 currency CHAR(3) NOT NULL,
 payable_amount DECIMAL(18,2) NOT NULL,
 status VARCHAR(32) NOT NULL,
 version INT NOT NULL DEFAULT 0,
 created_at DATETIME(3) NOT NULL,
 updated_at DATETIME(3) NOT NULL,
 UNIQUE KEY uk_merchant_order_no (order_no),
 KEY idx_morder_trade (trade_id),
 KEY idx_morder_buyer (buyer_id, created_at),
 KEY idx_morder_merchant (merchant_id, shop_id, created_at)
);
CREATE TABLE order_item (
 id BIGINT PRIMARY KEY,
 trade_id BIGINT NOT NULL,
 merchant_order_id BIGINT NOT NULL,
 merchant_id BIGINT NOT NULL,
 shop_id BIGINT NOT NULL,
 offer_id BIGINT NOT NULL,
 sku_id BIGINT NOT NULL,
 quantity INT NOT NULL,
 original_unit_price DECIMAL(18,2) NOT NULL,
 final_unit_price DECIMAL(18,2) NOT NULL,
 goods_amount DECIMAL(18,2) NOT NULL,
 discount_amount DECIMAL(18,2) NOT NULL,
 final_amount DECIMAL(18,2) NOT NULL,
 product_snapshot_json JSON NOT NULL,
 pricing_snapshot_json JSON NOT NULL,
 policy_snapshot_json JSON NOT NULL,
 created_at DATETIME(3) NOT NULL,
 KEY idx_order_item_order (merchant_order_id),
 KEY idx_order_item_offer (offer_id, created_at)
);
CREATE TABLE merchant_order_index (
 id BIGINT PRIMARY KEY,
 merchant_id BIGINT NOT NULL,
 shop_id BIGINT NOT NULL,
 order_no VARCHAR(64) NOT NULL,
 buyer_id BIGINT NOT NULL,
 order_status VARCHAR(32) NOT NULL,
 order_created_at DATETIME(3) NOT NULL,
 source_shard_key BIGINT NOT NULL,
 UNIQUE KEY uk_merchant_order_index_no (merchant_id, order_no),
 KEY idx_merchant_order_query (merchant_id, shop_id, order_status, order_created_at)
);
