package com.example.evcharging.finance.reconciliation;
import com.example.evcharging.framework.event.DomainEventEnvelope;import com.example.evcharging.framework.id.IdGenerator;import com.fasterxml.jackson.core.type.TypeReference;import com.fasterxml.jackson.databind.*;import org.springframework.dao.DuplicateKeyException;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.kafka.annotation.KafkaListener;import org.springframework.stereotype.Component;import org.springframework.transaction.annotation.Transactional;import java.time.*;
@Component public class FinanceTransactionFactConsumer {private static final String CONSUMER="transaction-fact-v1";private final JdbcTemplate jdbc;private final ObjectMapper mapper;private final IdGenerator ids;public FinanceTransactionFactConsumer(JdbcTemplate j,ObjectMapper m,IdGenerator i){jdbc=j;mapper=m;ids=i;}
 @KafkaListener(topics="${charging.payment-event-topic:ev.payment.payment.v1}",groupId="charging-finance-fact-v1") @Transactional public void consume(String raw)throws Exception{DomainEventEnvelope<JsonNode> e=mapper.readValue(raw,new TypeReference<DomainEventEnvelope<JsonNode>>(){});if(!mark(e))return;JsonNode p=e.payload();if("payment.payment.succeeded".equals(e.eventType())){String payment=req(p,"paymentNo"),order=req(p,"orderNo"),channel=req(p,"channel"),trade=req(p,"channelTradeNo");long station=p.path("stationId").asLong();if(station<=0)throw new IllegalArgumentException("stationId required");long amount=positive(p.path("amountFen").asLong());LocalDateTime at=time(p.path("successTime").asText(),e.occurredAt());LocalDateTime now=LocalDateTime.now();jdbc.update("""
 INSERT INTO finance_transaction_fact(id,tenant_id,payment_no,biz_order_no,station_id,channel,merchant_id,channel_trade_no,amount_fen,currency,payment_status,success_time,business_date,source_event_id,create_time,update_time)
 VALUES (?,?,?,?,?,?,'DEFAULT',?,?,'CNY','SUCCESS',?,?,?,?,?)
 ON DUPLICATE KEY UPDATE biz_order_no=VALUES(biz_order_no),station_id=VALUES(station_id),channel=VALUES(channel),channel_trade_no=VALUES(channel_trade_no),amount_fen=VALUES(amount_fen),payment_status='SUCCESS',success_time=VALUES(success_time),business_date=VALUES(business_date),update_time=VALUES(update_time)
 """,ids.nextId(),e.tenantId(),payment,order,station,channel,trade,amount,at,at.toLocalDate(),e.eventId(),now,now);}else if("payment.refund.succeeded".equals(e.eventType())){String refund=req(p,"refundNo"),payment=req(p,"paymentNo");long station=p.path("stationId").asLong();if(station<=0)throw new IllegalArgumentException("stationId required");long amount=positive(p.path("amountFen").asLong());LocalDateTime at=time(p.path("successTime").asText(),e.occurredAt());jdbc.update("""
 INSERT INTO finance_refund_fact(id,tenant_id,refund_no,payment_no,station_id,amount_fen,refund_status,success_time,business_date,source_event_id,create_time)
 VALUES (?,?,?,?,?,?,'SUCCESS',?,?,?,?) ON DUPLICATE KEY UPDATE amount_fen=VALUES(amount_fen),refund_status='SUCCESS',success_time=VALUES(success_time),business_date=VALUES(business_date)
 """,ids.nextId(),e.tenantId(),refund,payment,station,amount,at,at.toLocalDate(),e.eventId(),LocalDateTime.now());}}
 private boolean mark(DomainEventEnvelope<JsonNode> e){try{jdbc.update("INSERT INTO finance_event_inbox(id,consumer_name,event_id,event_type,processed_time) VALUES (?,?,?,?,?)",ids.nextId(),CONSUMER,e.eventId(),e.eventType(),LocalDateTime.now());return true;}catch(DuplicateKeyException x){return false;}}
 private static String req(JsonNode p,String n){String v=p.path(n).asText();if(v==null||v.isBlank())throw new IllegalArgumentException(n+" required");return v;}private static long positive(long v){if(v<=0)throw new IllegalArgumentException("amount must be positive");return v;}private static LocalDateTime time(String v,Instant f){try{return LocalDateTime.parse(v);}catch(Exception x){return LocalDateTime.ofInstant(f,ZoneOffset.UTC);}}
}
