CREATE TABLE security_deposit_account (
  id BIGINT NOT NULL,
  tenant_id BIGINT NOT NULL,
  agreement_id BIGINT NOT NULL,
  customer_id BIGINT NOT NULL,
  currency CHAR(3) NOT NULL,
  required_amount DECIMAL(18,2) NOT NULL,
  received_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
  deducted_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
  refunded_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
  reserved_refund_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
  available_balance DECIMAL(18,2) NOT NULL DEFAULT 0,
  status VARCHAR(32) NOT NULL,
  version INT NOT NULL DEFAULT 0,
  created_at DATETIME(3) NOT NULL,
  updated_at DATETIME(3) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_security_deposit_agreement (tenant_id, agreement_id),
  KEY idx_security_deposit_customer (tenant_id, customer_id, status)
);

CREATE TABLE security_deposit_transaction (
  id BIGINT NOT NULL,
  tenant_id BIGINT NOT NULL,
  deposit_account_id BIGINT NOT NULL,
  transaction_type VARCHAR(32) NOT NULL,
  source_type VARCHAR(32) NOT NULL,
  source_id BIGINT NULL,
  amount DECIMAL(18,2) NOT NULL,
  currency CHAR(3) NOT NULL,
  occurred_at DATETIME(3) NOT NULL,
  reason VARCHAR(512) NULL,
  idempotency_key VARCHAR(128) NULL,
  created_by BIGINT NULL,
  created_at DATETIME(3) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_deposit_tx_idem (tenant_id, deposit_account_id, idempotency_key),
  KEY idx_deposit_tx_account (tenant_id, deposit_account_id, occurred_at)
);

CREATE TABLE unidentified_collection (
  id BIGINT NOT NULL,
  tenant_id BIGINT NOT NULL,
  source_type VARCHAR(32) NOT NULL,
  source_id BIGINT NOT NULL,
  bank_account_id BIGINT NULL,
  provider_reference VARCHAR(128) NULL,
  payer_name_raw VARCHAR(256) NULL,
  payer_account_masked VARCHAR(128) NULL,
  currency CHAR(3) NOT NULL,
  amount DECIMAL(18,2) NOT NULL,
  received_at DATETIME(3) NOT NULL,
  memo_raw VARCHAR(1024) NULL,
  normalized_memo VARCHAR(1024) NULL,
  status VARCHAR(32) NOT NULL,
  claimed_customer_id BIGINT NULL,
  claimed_agreement_id BIGINT NULL,
  resulting_collection_id BIGINT NULL,
  claimed_by BIGINT NULL,
  claimed_at DATETIME(3) NULL,
  claim_reason VARCHAR(512) NULL,
  version INT NOT NULL DEFAULT 0,
  created_at DATETIME(3) NOT NULL,
  updated_at DATETIME(3) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_unidentified_source (tenant_id, source_type, source_id),
  KEY idx_unidentified_status (tenant_id, status, received_at)
);
