CREATE TABLE parking_space_profile (
    id BIGINT PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    resource_unit_id BIGINT NOT NULL,
    parking_no VARCHAR(64) NOT NULL,
    zone VARCHAR(64) NULL,
    floor_no VARCHAR(32) NULL,
    parking_type VARCHAR(32) NOT NULL,
    indoor TINYINT NOT NULL DEFAULT 1,
    charging_supported TINYINT NOT NULL DEFAULT 0,
    charger_meter_id BIGINT NULL,
    vehicle_size_limit VARCHAR(32) NULL,
    status VARCHAR(32) NOT NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    version INT NOT NULL DEFAULT 0,
    UNIQUE KEY uk_parking_profile_resource (tenant_id, resource_unit_id),
    UNIQUE KEY uk_parking_no (tenant_id, parking_no),
    KEY idx_parking_zone (tenant_id, zone, status)
);

CREATE TABLE utility_meter (
    id BIGINT PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    meter_no VARCHAR(64) NOT NULL,
    utility_type VARCHAR(32) NOT NULL,
    unit_code VARCHAR(16) NOT NULL,
    meter_scope VARCHAR(32) NOT NULL,
    reading_mode VARCHAR(32) NOT NULL,
    multiplier DECIMAL(20,8) NOT NULL DEFAULT 1,
    manufacturer VARCHAR(128) NULL,
    serial_no VARCHAR(128) NULL,
    installed_at DATETIME(3) NULL,
    status VARCHAR(32) NOT NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    version INT NOT NULL DEFAULT 0,
    UNIQUE KEY uk_utility_meter_no (tenant_id, meter_no),
    KEY idx_utility_meter_type (tenant_id, utility_type, status)
);

CREATE TABLE utility_meter_binding (
    id BIGINT PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    meter_id BIGINT NOT NULL,
    asset_id BIGINT NULL,
    space_id BIGINT NULL,
    resource_unit_id BIGINT NULL,
    allocation_method VARCHAR(32) NOT NULL,
    allocation_ratio DECIMAL(20,8) NULL,
    effective_from DATETIME(3) NOT NULL,
    effective_to DATETIME(3) NULL,
    status VARCHAR(32) NOT NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    version INT NOT NULL DEFAULT 0,
    KEY idx_meter_binding_meter (tenant_id, meter_id, status, effective_from, effective_to),
    KEY idx_meter_binding_resource (tenant_id, resource_unit_id, status, effective_from, effective_to)
);

CREATE TABLE utility_meter_reading (
    id BIGINT PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    meter_id BIGINT NOT NULL,
    reading_no VARCHAR(64) NOT NULL,
    period_start DATETIME(3) NOT NULL,
    period_end DATETIME(3) NOT NULL,
    previous_reading DECIMAL(20,6) NOT NULL,
    current_reading DECIMAL(20,6) NOT NULL,
    consumption DECIMAL(20,6) NOT NULL,
    source_type VARCHAR(32) NOT NULL,
    version_no INT NOT NULL DEFAULT 1,
    supersedes_reading_id BIGINT NULL,
    handover_order_id BIGINT NULL,
    evidence_file_id BIGINT NULL,
    anomaly_code VARCHAR(64) NULL,
    status VARCHAR(32) NOT NULL,
    submitted_by BIGINT NULL,
    submitted_at DATETIME(3) NULL,
    verified_by BIGINT NULL,
    verified_at DATETIME(3) NULL,
    billed_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    UNIQUE KEY uk_meter_reading_no (tenant_id, reading_no),
    UNIQUE KEY uk_meter_period_version (tenant_id, meter_id, period_start, period_end, version_no),
    KEY idx_meter_reading_period (tenant_id, meter_id, status, period_start, period_end),
    KEY idx_meter_reading_handover (tenant_id, handover_order_id)
);
