import { Button, Card, DatePicker, Form, Input, Space, Table, message } from 'antd';
import { useEffect, useState } from 'react';import dayjs from 'dayjs';import { ApiResponse, http } from '../api/http';
type Batch={batchNo:string;channel:string;merchantId:string;businessDate:string;status:string;localCount:number;channelCount:number;matchCount:number;differenceCount:number;completedTime:string};
type Diff={caseNo:string;differenceType:string;status:string;reason:string;resolution?:string;createTime:string};
type Schedule={channel:string;merchantId:string;zoneId:string;enabled:boolean;lastSuccessBusinessDate:string};
export default function ReconciliationPage(){
 const [batches,setBatches]=useState<Batch[]>([]);const [diffs,setDiffs]=useState<Diff[]>([]);const [schedules,setSchedules]=useState<Schedule[]>([]);
 const load=async()=>{const [a,b,c]=await Promise.all([http.get<ApiResponse<Batch[]>>('/admin-api/v1/finance/reconciliation/batches'),http.get<ApiResponse<Diff[]>>('/admin-api/v1/finance/reconciliation/differences?status=OPEN'),http.get<ApiResponse<Schedule[]>>('/admin-api/v1/finance/reconciliation-schedules')]);setBatches(a.data.data||[]);setDiffs(b.data.data||[]);setSchedules(c.data.data||[])};useEffect(()=>{void load()},[]);
 const run=async(v:any)=>{await http.post('/admin-api/v1/finance/reconciliation/run',{requestId:crypto.randomUUID(),channel:v.channel||'MOCK',merchantId:v.merchantId||'DEFAULT',businessDate:(v.businessDate||dayjs()).format('YYYY-MM-DD')});message.success('Reconciliation completed');await load()};
 const saveSchedule=async(v:any)=>{await http.post('/admin-api/v1/finance/reconciliation-schedules',{channel:v.channel||'MOCK',merchantId:v.merchantId||'DEFAULT',zoneId:v.zoneId||'Asia/Shanghai',enabled:true});message.success('T+1 schedule saved');await load()};
 const upload=async(file:File)=>{const data=new FormData();data.append('file',file);await http.post('/admin-api/v1/finance/channel-bills/import-raw',data,{headers:{'Content-Type':'multipart/form-data'}});message.success('Raw channel bill archived and imported');await load()};
 return <Space direction="vertical" size={16} style={{width:'100%'}}>
  <Card title="Raw channel bill archive + normalized JSON import"><Space><input type="file" accept="application/json,.json" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f)}}/><span>Archive uses SHA-256 before normalization.</span></Space></Card>
  <Card title="T+1 automatic reconciliation"><Form layout="inline" onFinish={saveSchedule} initialValues={{channel:'MOCK',merchantId:'DEFAULT',zoneId:'Asia/Shanghai'}}><Form.Item name="channel"><Input placeholder="Channel"/></Form.Item><Form.Item name="merchantId"><Input placeholder="Merchant"/></Form.Item><Form.Item name="zoneId"><Input placeholder="Asia/Shanghai"/></Form.Item><Button htmlType="submit" type="primary">Save schedule</Button></Form><Table<Schedule> size="small" rowKey={r=>`${r.channel}:${r.merchantId}`} dataSource={schedules} columns={[{title:'Channel',dataIndex:'channel'},{title:'Merchant',dataIndex:'merchantId'},{title:'Zone',dataIndex:'zoneId'},{title:'Enabled',render:(_,r)=>String(r.enabled)},{title:'Last T+1',dataIndex:'lastSuccessBusinessDate'}]}/></Card>
  <Card title="Exact reconciliation"><Form layout="inline" onFinish={run} initialValues={{channel:'MOCK',merchantId:'DEFAULT',businessDate:dayjs()}}><Form.Item name="channel"><Input/></Form.Item><Form.Item name="merchantId"><Input/></Form.Item><Form.Item name="businessDate"><DatePicker/></Form.Item><Button type="primary" htmlType="submit">Run</Button></Form></Card>
  <Table<Batch> rowKey="batchNo" dataSource={batches} columns={[{title:'Batch',dataIndex:'batchNo'},{title:'Date',dataIndex:'businessDate'},{title:'Local',dataIndex:'localCount'},{title:'Channel',dataIndex:'channelCount'},{title:'MATCH',dataIndex:'matchCount'},{title:'Difference',dataIndex:'differenceCount'},{title:'Status',dataIndex:'status'}]}/>
  <Card title={`Open Difference Cases (${diffs.length})`}><Table<Diff> rowKey="caseNo" dataSource={diffs} columns={[{title:'Case',dataIndex:'caseNo'},{title:'Type',dataIndex:'differenceType'},{title:'Reason',dataIndex:'reason'},{title:'Status',dataIndex:'status'}]}/></Card>
 </Space>;
}
