import { Button, Card, DatePicker, Form, Input, InputNumber, Space, Table, message } from 'antd';
import { useEffect, useState } from 'react';import dayjs from 'dayjs';import { ApiResponse, http } from '../api/http';
type Rule={ruleCode:string;ruleName:string;versionId:number;versionNo:number;status:string;effectiveFrom:string};
type Batch={batchNo:string;businessDate:string;ruleVersionId:number;status:string;sourceCount:number;amountFen:number;createdBy:number;approvedBy?:number;completedTime:string};
export default function SettlementPage(){
 const [rules,setRules]=useState<Rule[]>([]);const [batches,setBatches]=useState<Batch[]>([]);
 const load=async()=>{const [a,b]=await Promise.all([http.get<ApiResponse<Rule[]>>('/admin-api/v1/finance/settlement/rules'),http.get<ApiResponse<Batch[]>>('/admin-api/v1/finance/settlement/batches')]);setRules(a.data.data||[]);setBatches(b.data.data||[])};useEffect(()=>{void load()},[]);
 const rule=async(v:any)=>{await http.post('/admin-api/v1/finance/settlement/rules',{ruleCode:v.ruleCode||'DEFAULT',ruleName:v.ruleName||'Default Rule',versionNo:Number(v.versionNo||1),effectiveFrom:dayjs().format('YYYY-MM-DDTHH:mm:ss'),items:[{participantType:'OPERATOR',participantId:'OPERATOR-DEFAULT',ratioBps:Number(v.operatorBps||7000)},{participantType:'STATION_OWNER',participantId:'STATION-OWNER-DEFAULT',ratioBps:Number(v.stationBps||2000)},{participantType:'PLATFORM',participantId:'PLATFORM',ratioBps:Number(v.platformBps||1000)}]});message.success('Rule published');await load()};
 const run=async(v:any)=>{await http.post('/admin-api/v1/finance/settlement/run',{requestId:crypto.randomUUID(),businessDate:(v.businessDate||dayjs()).format('YYYY-MM-DD'),ruleVersionId:Number(v.ruleVersionId)});message.success('Settlement calculated; approval required');await load()};
 const approve=async(no:string)=>{await http.post(`/admin-api/v1/finance/settlement/${no}/approve`,{comment:'Approved in dev UI'});message.success('Settlement approved and posted');await load()};
 const reject=async(no:string)=>{await http.post(`/admin-api/v1/finance/settlement/${no}/reject`,{comment:'Rejected in dev UI'});message.success('Settlement rejected');await load()};
 return <Space direction="vertical" size={16} style={{width:'100%'}}><Card title="Publish settlement rule"><Form layout="inline" onFinish={rule} initialValues={{ruleCode:'DEFAULT',ruleName:'Default Rule',versionNo:1,operatorBps:7000,stationBps:2000,platformBps:1000}}><Form.Item name="ruleCode"><Input/></Form.Item><Form.Item name="ruleName"><Input/></Form.Item><Form.Item name="versionNo"><InputNumber min={1}/></Form.Item><Form.Item name="operatorBps"><InputNumber min={0} max={10000}/></Form.Item><Form.Item name="stationBps"><InputNumber min={0} max={10000}/></Form.Item><Form.Item name="platformBps"><InputNumber min={0} max={10000}/></Form.Item><Button type="primary" htmlType="submit">Publish</Button></Form></Card><Card title="Calculate settlement (maker user 10001)"><Form layout="inline" onFinish={run} initialValues={{businessDate:dayjs()}}><Form.Item name="businessDate"><DatePicker/></Form.Item><Form.Item name="ruleVersionId"><InputNumber placeholder="Rule Version ID"/></Form.Item><Button type="primary" htmlType="submit">Calculate</Button></Form></Card><Table<Rule> rowKey="versionId" dataSource={rules} columns={[{title:'Rule',dataIndex:'ruleCode'},{title:'Version ID',dataIndex:'versionId'},{title:'Version',dataIndex:'versionNo'},{title:'Status',dataIndex:'status'}]}/><Table<Batch> rowKey="batchNo" dataSource={batches} columns={[{title:'Batch',dataIndex:'batchNo'},{title:'Date',dataIndex:'businessDate'},{title:'Sources',dataIndex:'sourceCount'},{title:'Amount',render:(_,r)=>`¥${(r.amountFen/100).toFixed(2)}`},{title:'Status',dataIndex:'status'},{title:'Maker',dataIndex:'createdBy'},{title:'Action',render:(_,r)=>r.status==='PENDING_APPROVAL'?<Space><Button size="small" onClick={()=>approve(r.batchNo)}>Approve as 10002</Button><Button size="small" danger onClick={()=>reject(r.batchNo)}>Reject</Button></Space>:null}]}/></Space>;
}
