CREATE TABLE utility_usage_period (
  id BIGINT NOT NULL,
  tenant_id BIGINT NOT NULL,
  agreement_id BIGINT NOT NULL,
  agreement_item_id BIGINT NULL,
  resource_unit_id BIGINT NOT NULL,
  meter_id BIGINT NOT NULL,
  utility_type VARCHAR(32) NOT NULL,
  period_start DATETIME(3) NOT NULL,
  period_end DATETIME(3) NOT NULL,
  start_reading_id BIGINT NOT NULL,
  end_reading_id BIGINT NOT NULL,
  start_value DECIMAL(20,6) NOT NULL,
  end_value DECIMAL(20,6) NOT NULL,
  meter_multiplier DECIMAL(20,8) NOT NULL DEFAULT 1,
  raw_usage DECIMAL(20,6) NOT NULL,
  adjusted_usage DECIMAL(20,6) NOT NULL,
  allocation_method VARCHAR(32) NOT NULL,
  allocation_factor DECIMAL(20,8) NULL,
  billable_usage DECIMAL(20,6) NOT NULL,
  tariff_plan_id BIGINT NOT NULL,
  tariff_version INT NOT NULL,
  estimated_flag TINYINT NOT NULL DEFAULT 0,
  correction_of_usage_period_id BIGINT NULL,
  calculation_trace_json JSON NOT NULL,
  status VARCHAR(32) NOT NULL,
  version INT NOT NULL DEFAULT 0,
  created_at DATETIME(3) NOT NULL,
  updated_at DATETIME(3) NOT NULL,
  PRIMARY KEY (id),
  KEY idx_usage_period_agreement (tenant_id, agreement_id, utility_type, period_start),
  KEY idx_usage_period_meter (tenant_id, meter_id, period_start, period_end),
  KEY idx_usage_period_status (tenant_id, status, period_end)
);
